cmake_minimum_required(VERSION 3.10)


# Set used languages to support assembler build as well.
enable_language(CXX C ASM)

# Initialize lists.
set(CRASHHANDLER_HEADERS "" PARENT_SCOPE)
set(CRASHHANDLER_SOURCES "" PARENT_SCOPE)
set(CRASHHANDLER_INCLUDE_DIRS "" PARENT_SCOPE)


list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/qcrashhandler.h)
list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/qcrashhandler.cpp)

list(APPEND CRASHHANDLER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR})
list(APPEND CRASHHANDLER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src)


# windows
if (WIN32)

    # headers
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/windows/string_utils-inl.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/windows/guid_string.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/windows/handler/exception_handler.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/windows/common/ipc_protocol.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/google_breakpad/common/minidump_format.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/google_breakpad/common/breakpad_types.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/windows/crash_generation/crash_generation_client.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/scoped_ptr.h)

    # sources
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/windows/handler/exception_handler.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/windows/string_utils.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/windows/guid_string.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/windows/crash_generation/crash_generation_client.cc)

# linux
elseif (UNIX)

    # copy linux syscall support dependency
    set(LINUX_SYSCALL_SRC ${CMAKE_CURRENT_LIST_DIR}/../deps/linux_syscall.git/linux_syscall_support.h)
    set(LINUX_SYSCALL_TARG_PATH ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/third_party/lss)
    set(LINUX_SYSCALL_TARG ${LINUX_SYSCALL_TARG_PATH}/linux_syscall_support.h)
    if (NOT EXISTS ${LINUX_SYSCALL_TARG_PATH})
        execute_process(COMMAND mkdir ${LINUX_SYSCALL_TARG_PATH} RESULT_VARIABLE retval)
        if (${retval} EQUAL 0)
            message(STATUS "Created directory ${LINUX_SYSCALL_TARG_PATH}")
        else ()
            message(FATAL_ERROR "Directory ${LINUX_SYSCALL_TARG_PATH} creation has failed")
        endif ()
    endif ()
    execute_process(COMMAND cp -rf ${LINUX_SYSCALL_SRC} ${LINUX_SYSCALL_TARG} RESULT_VARIABLE retval)
    if (${retval} EQUAL 0)
        message(STATUS "Copied file ${LINUX_SYSCALL_SRC} to ${LINUX_SYSCALL_TARG}")
    else ()
        message(FATAL_ERROR "File ${LINUX_SYSCALL_SRC} copying to ${LINUX_SYSCALL_TARG} has failed")
    endif ()

    # headers
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/cpu_set.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/proc_cpuinfo_reader.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/handler/exception_handler.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/crash_generation/crash_generation_client.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/handler/minidump_descriptor.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/minidump_writer.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/line_reader.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/linux_dumper.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/linux_ptrace_dumper.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/directory_reader.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/pe_file.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/log/log.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/minidump_file_writer-inl.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/minidump_file_writer.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/linux_libc_support.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/eintr_wrapper.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/ignore_ret.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/file_id.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/memory_mapped_file.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/safe_readlink.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/guid_creator.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/elfutils.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/elfutils-inl.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/elf_gnu_compat.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/using_std_string.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/basictypes.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/memory_range.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/string_conversion.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/convert_UTF.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/google_breakpad/common/minidump_format.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/google_breakpad/common/minidump_size.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/google_breakpad/common/breakpad_types.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/scoped_ptr.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/third_party/lss/linux_syscall_support.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/dump_writer_common/mapping_info.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/dump_writer_common/raw_context_cpu.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/dump_writer_common/thread_info.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/dump_writer_common/ucontext_reader.h)
    list(APPEND CRASHHANDLER_HEADERS ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/microdump_writer/microdump_writer.h)

    # sources
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/crash_generation/crash_generation_client.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/handler/exception_handler.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/handler/minidump_descriptor.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/minidump_writer.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/linux_dumper.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/linux_ptrace_dumper.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/minidump_writer/pe_file.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/log/log.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/minidump_file_writer.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/linux_libc_support.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/file_id.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/memory_mapped_file.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/safe_readlink.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/guid_creator.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/elfutils.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/linux/breakpad_getcontext.S)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/string_conversion.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/common/convert_UTF.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/dump_writer_common/thread_info.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/dump_writer_common/ucontext_reader.cc)
    list(APPEND CRASHHANDLER_SOURCES ${CMAKE_CURRENT_LIST_DIR}/../deps/breakpad.git/src/client/linux/microdump_writer/microdump_writer.cc)

else ()
    message(FATAL_ERROR "Platform isn't supported")
endif ()
